version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barbearia_web
    ports:
      - "9001:9001"
    volumes:
      - .:/app   # Mantém volume para desenvolvimento; cuidado com estrutura local
    restart: always
